Add exit code capture and display in main.yml workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,3 +24,5 @@ jobs:
       - name: Code-Formatierung durchführen (black)
         run: |
           black . && git diff --exit-code
+          exit_code=$? # Capture the exit code
+          echo "The exit code is $exit_code"
